# 29/08 14h UTC — Ronda do Vigia (sensor, regra 14-A + 14-C)

`git checkout main && git pull --ff-only origin main` → trouxe **2 commits** novos
(`565d8a9` merge do PR #113 SGP + `6a39dcc`); a árvore ficou em `565d8a9`. Índice de
ordens lido antes de tocar em qualquer coisa. Ordem vigente do assunto:
`2026-08-27_vigia_so_erro_de_sistema.md` (14-C). Também valem
`2026-08-20_dono_da_fila_e_fila_zerada.md` (14-A), a `2026-08-20_REGRA_FINAL_CREDITO.md`
(ENCERRADA — não reabri) e a rotina `e-mail_tecnico.md`.

Ronda anterior: **12h UTC**. Esta: **14h UTC**. Intervalo de 2h, no ritmo.

---

## Placar

| | |
|---|---|
| Incidentes abertos no fim | **6** — **2 de aluno** (`99`, `181`), **4 técnicos** (`180`, `183`, `184`, `185`) |
| **Abertos por mim nesta ronda** | **1** — o `185` (§1) |
| **Anotados por mim** | **1** — o Luan Marçal, re-medido e confirmado (§2) |
| **Fechados que voltaram a disparar** | **0** — só o `#8` de sempre, última ocorrência 22/08, há 7 dias |
| Fechados na janela | **0** |
| Abertos por outros na janela | **1** — o `184` (Frank, 12:52Z) |
| E-mails novos de aluno desde as 12h | **0** |
| E-mails **enviados** na janela | **3** — `315` Johnathan 13:50Z, `316` Kelinn 13:55Z, `317` Fernando 14:00Z |
| Aluno cobrando 2ª vez ou mais | **0 novos** |
| Aluno com promessa de retorno e **nenhum** retorno | **0** — o Johnathan **foi respondido** (§3) |
| Fila de não-lidos da Fast | **0**. **Não toquei em não-lido** |
| Gerações em 24h | **112** — 111 `ready`, **1 `failed`** (a mesma de 18:16Z, pré-fix) |
| Gerações presas (qualquer idade) | **0** |
| Estorno da única falha | **OK** — casado por `ref_id`, conferido por `ref_type` |
| Cenas de estúdio em 24h | **37**, todas `ready` |
| Imagens em 24h | **169** — 168 `ready`, 1 `generating` **de 1 minuto** (em voo, não preso) |
| Vozes criadas em 24h | **17**, todas `ready` |
| `training_jobs` preso >30min | **1** — o órfão de 25/08, voz já `ready`, escrituração pendente |
| `awaiting_training` +24h | **16 vozes / 15 alunos**, média 24,8 dias, pior 46,4 — **estável pela 10ª janela** |
| PRs abertos | **24** (+1: o `114`, do `184`) |
| Árvore de trabalho suja | **NÃO** — as 106 linhas soltas do §7 das 12h **viraram commit e PR** (§4) |
| Incidente que eu fechei, reabri ou reclassifiquei | **nenhum** |
| Aluno que eu respondi / rascunho que escrevi | **nenhum** |
| Crédito, acesso ou assinatura que eu toquei | **nenhum** |

Contagem **sem cláusula de assinatura** e **pelo complemento**
(`status not in ('fixed','ignored')`). Conferido pelo `group by status` da tabela
inteira: **139 `fixed`, 32 `ignored`, 6 `investigating`, 0 `open`** = 177 linhas.
Bate com as 175 das 12h + o `184` (Frank) + o `185` (meu).

---

## 1. ABRI o `185` — a lista canônica de estorno envelheceu calada, e o guarda
##    que existe pra pegar isso nunca é chamado

**Esta é a única coisa que eu abri nesta ronda, e é de DINHEIRO — então segue o
§3 da 14-C à risca: `arquivo:linha` dos dois lados e casamento por `ref_id`.**

`_frank/ferramentas/_estornos.cjs:27-38` é a fonte única de "quais `ref_type`
significam *devolvemos crédito*". Ela nasceu do chamado **#113** (commit `c7c9887`,
23/08) justamente porque conferir estorno por critério estreito produz **falso
negativo** — o aluno já estornado parece não estornado — e foi isso que quase pagou
13 alunos em dobro em 20/08.

A lista tem 9 entradas. **Falta `studio_audio_refund`.**

| | |
|---|---|
| onde o débito e o estorno nascem | `frontend/src/lib/studio/finalize.ts:104` — `handleTechFailure({ debitRefType: 'studio_audio', refundRefType: 'studio_audio_refund' })`. É o F0 do Vídeo Estúdio (limpeza de áudio), produção |
| o que a lista responde | `ehEstorno('studio_audio_refund')` → **`false`** (`_estornos.cjs:51`) |

**A prova no banco, casada por `ref_id`** (nunca por `kind`, nunca por timestamp):
7 linhas `studio_audio_refund`, **29/08 04:13:48Z → 04:23:57Z**, **+3.850 cr**, todas
da `priscillarosseti@hotmail.com`. Somando o **sinal** do `amount` por `ref_id`, os
7 projetos dão **saldo ZERO** (2 linhas cada: `studio_audio` −N e
`studio_audio_refund` +N). **Ela FOI estornada, integralmente — e a lista diz que
não.** São 3.850 cr de falso negativo esperando alguém "consertar".

**O agravante:** `_estornos.cjs:59-71` tem `conferirListaCompleta(db)`, com esta
docstring na linha 56: *"Lista fixa envelhece calada - e envelhecer calada aqui
custa dinheiro."* Ela varre `credit_transactions` com `amount>0` e acusa todo
`ref_type` que case `/refund|estorn|devolu/i` e não esteja na lista.
`studio_audio_refund` **casa o regex** — o guarda pegaria isto no primeiro dia.
Varredura no repo por `conferirListaCompleta` (fora de `node_modules`/`.next`):
definição em `:59`, export em `:73`, **CHAMADAS: ZERO**. Nenhuma ferramenta, nenhum
cron, nenhum teste roda o guarda. A lista envelheceu exatamente do jeito que o
próprio autor previu por escrito.

**As 3 checagens do §3, feitas antes de abrir:**

1. **Já existe?** Varri a fila **aberta e fechada** por `title`/`signature` com
   `estorno|ref_type|refund`: 25 chamados, 24 deles `fail-burst:<tipo>_refund:<aluno>`
   (rajada de falha, outra classe). O único parente é o **#113**, `fixed` — e ele é
   sobre o critério da **ordem** de 20/08, e foi ele que **criou** esta lista. O `185`
   é sobre a lista que aquele fix produziu ter envelhecido e sobre o guarda dela nunca
   rodar. Classe nova. **Não reabri o #113.**
2. **Já foi corrigido?** `git log` de `_estornos.cjs` desde 22/08: **um único commit**,
   o `c7c9887` que o criou. `gh pr list --state open` (24 PRs): **nenhum** toca
   `_estornos.cjs` nem `studio_audio_refund` — o `114`, aberto hoje 13:57Z, é do
   Drive/quota. Não estou pedindo pra ninguém refazer trabalho pronto.
3. **Dinheiro?** Sim, e por isso os dois requisitos estão no chamado.
   ⚠️ **NÃO HÁ ESTORNO A FAZER.** O dinheiro da Priscilla está **liquidado**. Este
   chamado pede o contrário de pagar: ele existe pra que ninguém **pague de novo**.
   Não toquei em crédito.

**Teste de bolso da 14-C** — *"se o código/infra estivesse certo, isso teria
acontecido?"* **Não**: a lista é código, o guarda é código, e o guarda existe
justamente pra impedir a divergência que se instalou. **Vira chamado.**

**O que eu NÃO afirmo:** (a) que alguém já pagou em dobro — procurei e não achei
estorno duplicado nos 7 `ref_id` (saldo zero, 2 linhas cada); o dano até aqui é
**potencial**, e o #113 mostra que só não virou dinheiro perdido porque alguém
conferiu à mão a tempo. (b) que `finalize.ts:104` está errado — o caminho de estorno
funciona; errado está o **inventário** que deveria conhecê-lo. (c) que este é o único
faltante no futuro — afirmo que **hoje** ele é o único `ref_type` de estorno vivo
fora da lista, conferido contra os 21 `ref_type` positivos distintos do banco.

**Risco secundário, registrado como não-medido:** `conferirListaCompleta` faz
`.limit(5000)` **sem paginar**. Hoje há 2.483 linhas com `amount>0`, então o teto
ainda não morde. **Não testei** se o PostgREST rebaixa esse `limit` pro teto de 1000
do projeto — se rebaixar, o guarda já nasce parcialmente cego e a armadilha do corte
silencioso volta pela porta do fundo. Quem consertar, pagine e confira o `count`.

## 2. Luan Marçal — RE-MEDI por causa do `184`, e o diagnóstico continua CERTO

O Frank abriu às 12:52Z o **`184`**: *"Quota exceeded" do Google lido como "arquivo
não está público"* — `drive.ts:101` trata **todo** `text/html` como privado. A nota
dele (13:51Z) reproduz a causa ao vivo no Johnathan, com prova.

Isso põe a minha conclusão das 12h sobre o **Luan** em xeque, então **fui medir de
novo em vez de confiar no que eu mesmo escrevi**. Se o Luan fosse o mesmo defeito, o
fix do `184` o destravaria sozinho e a decisão que eu pedi ao Johnny seria dispensável.

Arquivo `1uIewwwiBga3FRrwJDZ2nauQw7QaTVfd6`, duas requisições agora (14:13Z), pelo
mesmo endpoint e com o mesmo header `Range: bytes=0-` que o `downloadDriveFile` usa:

| tentativa | desfecho |
|---|---|
| 1 | `200 text/html`, 904.998 B, URL final `accounts.google.com/v3/signin/identifier?…flowEntry=ServiceLogin` |
| 2 | `200 text/html`, 905.131 B, **mesma** cadeia |

Corpo salvo: é a página de login do Google (`<base href="https://accounts.google.com/v3/signin/">`).
**Não é `Quota exceeded`** — o corpo do quota, medido pelo Frank no Johnathan, tem
2.009 B e `<title>Google Drive - Quota exceeded</title>`. Aqui são ~905 kB de tela de
login, **duas vezes, com 2h de distância da medição das 12h**. Cota é transitória e se
recupera em segundos; isto não se moveu.

**Conclusão mantida: o arquivo do Luan realmente não está público, e a mensagem que
ele recebeu está correta.** Continua **não sendo chamado** pela 14-C. E o `184` está
certo pelo outro lado: são de fato **dois** casos distintos que hoje caem no mesmo
balde, e o helper de 3 vias que o PR `114` propõe (quota × login × HTML desconhecido)
produziria a mensagem certa para **os dois** — a do Luan inclusive.

**Estado dele, sem mudança:** `luanmarcal.com@gmail.com`, uid `6284e233`, conta 28/08,
**pagou 29/08** (assinatura `active`, acesso até 29/09, 98.425 créditos). **0 vozes**,
travado desde **05:42Z** — agora **~8,5h**. As 5 imagens passaram (`ready`), o áudio não.

**A decisão que eu pedi às 12h continua sem resposta**, e o relógio andou 2h: pagante
do dia 1, parado, **e a bola é dele** — não há nada no nosso lado pra destravar. Ou
alguém cutuca hoje, ou a automação espera um retorno que pode não vir. Não escrevi
pra ele e não abri chamado.

## 3. Johnathan — a promessa foi cumprida, o caso tem dono e SAIU da minha lista

Nas 3 rondas anteriores eu vinha contando as horas de espera dele (chegou a ~8h com
duas promessas furadas). **Isso acabou nesta janela**, e registro porque o número que
eu venho reportando mudou de sinal:

- **`184` aberto** às 12:52Z, com a causa reproduzida ao vivo (15 arquivos na pasta,
  os 4 primeiros baixam íntegros, do 5º em diante o Drive devolve 2.009 B de
  `Quota exceeded`; minutos depois o **mesmo** `fileId` volta `206 video/mp4`).
- **PR `114`** (`feat/onboarding-drive-quota`) aberto 13:57Z.
- **E-mail enviado** a ele às 13:50Z (Enviados uid `315`): *"Seu link está certo - o
  problema era nosso, e já estamos corrigindo"*.
- Decisão registrada no chamado que eu **apoio**: **não re-disparar o import dele
  antes do fix**, porque com 15 arquivos a cota estouraria no meio e ele levaria a
  **terceira** acusação injusta.

**Não abri chamado** (é ocorrência do `180`/`184`, não classe nova) e **não toquei**.
O alerta que eu venho carregando **continua valendo pro próximo que pegar**: os
arquivos do link ANTIGO eram peças de divulgação (ACADEMY AD / LAB AD / SOLUTIONS AD).
Se o link novo levar ao mesmo material, **conferir locutor único por F0 antes de
disparar treino** — armadilha já medida no caso Marcelo (`f6f82819`), em que o clone
saiu com a voz de outra pessoa. O PR **50** existe exatamente pra isso, aberto desde 25/08.

## 4. Processo — as 106 linhas soltas do §7 das 12h foram salvas

Registro o desfecho porque o risco era meu de levantar e é justo dizer que sumiu:
a árvore está **limpa** (`git status --porcelain` vazio). Os arquivos que estavam sem
branch, sem commit e sem PR (`import/route.ts`, `import.ts`, `veredito-audio.ts` e o
novo `video-audio.ts`) agora estão nos commits `0755ab2` e `d4778da`, na branch
`feat/onboarding-drive-quota` — a mesma do PR `114`. **Um `checkout` errado não leva
mais nada.** Sem chamado, como manda a 14-C.

## 5. Fechados que voltaram a disparar

**Zero novos.** A única linha com `last_seen_at > resolved_at` na tabela inteira
continua sendo o **`#8`** ("Treino de voz: áudio insuficiente/sem fala limpa"),
fechado em 09/08, último disparo **22/08 19:26** — 7 dias atrás, mais uma janela sem
se mexer. Segue como registro, sem ação, e **não reabri**.

## 6. Dinheiro da janela — nada novo, e nada pendurado

Nenhuma falha nova em 24h além da já conhecida: geração `086970cd`, 28/08 18:16:10Z,
`executionTimeout exceeded`, **pré-fix**. Liquidada em 8min18s, casada por `ref_id`
(−400 `ref_type=generation`, +400 `ref_type=generation_refund` com
`kind=extra_purchase` — o `kind` que engana quem confere por ele).

Estornos nas 24h, por `ref_type`: `support_refund` 12 (+12.720),
`studio_audio_refund` 7 (+3.850), `video_clone_refund` 1 (+630), `image_refund` 1
(+525), `generation_refund` 1 (+400). **Idênticos aos das 12h — nenhum movimento
novo.** Nada pendurado. Foi ao conferir esta mesma linha que o `185` apareceu: o
`studio_audio_refund` está no banco há 10h e **não está na lista** que decide se
alguém foi estornado.

## 7. Caixa — nenhum e-mail novo de aluno, e o não-lido intocado

`ler_caixa.cjs --ultimos 25 --corpo 2500`: leitura pura (`BODY.PEEK`, só `SEEN`).
**Não toquei em não-lido.** Fila de não-lidos da Fast: **0**.

**Nenhum e-mail novo de aluno desde as 12h** — nem desde as 10h. O mais recente do
INBOX continua sendo o **uid 373** (Johnathan, 04:15Z).

Procurei os sinais de escalação silenciosa (*"a equipe vai verificar"*, *"vou chamar
alguém da equipe"*, aluno cobrando 2ª vez): **nenhum caso novo sem chamado**. Antes de
descartar qualquer um, conferi se já havia resposta enviada.

O que se moveu foi nos **Enviados**, e é tudo trabalho do dono da fila, não meu:

- **uid 315, 13:50Z, Johnathan** — §3.
- **uid 316, 13:55Z, Kelinn** (`kelinnavelar@icloud.com`) — *"Faltaram 26 segundos
  para a sua voz - e nada foi cobrado"*. Ela é uma das **2 contas com acesso vivo,
  crédito e nenhuma voz pronta** que a varredura acusa (voz `a046ede6`,
  `rejected_too_short`, 16 dias). **Foi respondida nesta janela.** A outra é o
  `marcelopersonalthe32@gmail.com` (voz `f6f82819`, multi-locutor, 19 dias), que
  **continua sem retorno** — é o caso que o PR `50` endereça.
- **uid 317, 14:00Z, Fernando** (`fmgimael@gmail.com`) — compra aprovada, falta criar
  conta. Fluxo normal, sem pendência.

**Luciano (`99`)**, para o registro: recebeu o retorno técnico às 10:47Z (uid `314`) e
**não respondeu** até agora. O chamado segue `investigating`; fechar ou não é do dono,
**não mexi**.

## 8. O que eu NÃO fiz

- Não fechei, não reabri e não reclassifiquei **nenhum** incidente.
- Abri **um só** chamado, o `185`, de dinheiro, com `arquivo:linha` dos dois lados e
  casamento por `ref_id` — e ele pede pra **não** pagar, não pra pagar.
- **Re-medi a minha própria conclusão das 12h** (o Luan) em vez de repeti-la, porque o
  `184` a colocou em dúvida. Ela se sustentou; se não tivesse se sustentado, eu diria.
- Não respondi aluno e **não escrevi rascunho de e-mail** (armadilha do lucvila, 20/08).
- Não toquei em crédito, acesso ou assinatura.
- Não toquei em e-mail não-lido.
- Não mexi em código — nem no `_estornos.cjs`, que é o objeto do `185`.
- Não abri o link do Drive do Johnathan nem disparei importação/treino.
