# 29/08 12h UTC — Ronda do Vigia (sensor, regra 14-A + 14-C)

`git checkout main && git pull --ff-only origin main` → **já atualizado**, nenhum
commit novo desde a ronda das 10h (o último em `origin/main` é o `21a5f7e`, que é
o log daquela ronda). Índice de ordens lido antes de tocar em qualquer coisa.
Ordem vigente do assunto: `2026-08-27_vigia_so_erro_de_sistema.md` (14-C).
Também valem `2026-08-20_dono_da_fila_e_fila_zerada.md` (14-A), a
`2026-08-20_REGRA_FINAL_CREDITO.md` (ENCERRADA — não reabri) e a rotina
`e-mail_tecnico.md`.

Ronda anterior: **10h UTC**. Esta: **12h UTC**. Intervalo de 2h, no ritmo.

---

## Placar

| | |
|---|---|
| Incidentes abertos no fim | **5** — **3 de aluno** (`99`, `173`, `181`), **2 técnicos** (`180`, `183`) |
| **Abertos por mim nesta ronda** | **0** |
| **Anotados por mim** | **1** — o caso Luan Marçal (§1), que pela 14-C **não** vira chamado |
| **Fechados que voltaram a disparar** | **0** — só o `#8` de sempre, última ocorrência 22/08, há 7 dias |
| Fechados na janela | **1** — o `182` (12:11:18Z, por `agent`, como `ignored`) |
| E-mails novos de aluno desde as 10h | **0** |
| E-mails **enviados** na janela | **1** — o `314`, pro Luciano, 10:47Z |
| Aluno cobrando 2ª vez ou mais | **0 novos** |
| Aluno com promessa de retorno e **nenhum** retorno | **1** — **Johnathan**, ~8h (§2) |
| Fila de não-lidos da Fast | **0**. **Não toquei em não-lido** |
| Gerações em 24h | **125** — 124 `ready`, **1 `failed`** (a mesma de 18:16Z, pré-fix) |
| Gerações presas (qualquer idade) | **0** |
| Estorno da única falha | **OK** — casado por `ref_id`, conferido por `ref_type` (§5) |
| Cenas de estúdio em 24h | **37**, todas `ready` |
| Projetos de estúdio em estado transitório | **0** — nada em `processing`/`queued` |
| `training_jobs` preso >30min | **1** — o órfão de 25/08, ~106,6h em `queued`, já medido |
| `awaiting_training` +24h | **16 vozes / 15 alunos**, média 24,7 dias, pior 46,4 — **estável pela 9ª janela** |
| PRs abertos | **23** |
| Incidente que eu fechei, reabri ou reclassifiquei | **nenhum** |
| Aluno que eu respondi / rascunho que escrevi | **nenhum** |
| Crédito, acesso ou assinatura que eu toquei | **nenhum** |

Contagem **sem cláusula de assinatura** e **pelo complemento**
(`status not in ('fixed','ignored')`). Conferido pelo `group by status` da tabela
inteira: **138 `fixed`, 32 `ignored`, 5 `investigating`, 0 `open`** = 175 linhas.
Bate com as 174 da ronda das 10h + o `183` que eu abri lá.

---

## 1. PRECISA DE DECISÃO — pagante do dia 1 travado no onboarding, e o
##    diagnóstico do sistema está CERTO (por isso não abri chamado)

**Luan Marçal** — `luanmarcal.com@gmail.com`, uid `6284e233`.
Conta criada **28/08**, **pagou em 29/08** (assinatura `active`, acesso até
**29/09**, 98.425 créditos, recarga de ciclo de +100.000 às 05:48Z).
**0 vozes.** Travado desde **05:42Z** — ~6,5h no fecho desta ronda.

O onboarding rodou até o meio: as 5 imagens dele entraram (`ready`, 05:42) e o
áudio parou. Ele recebeu três e-mails automáticos em 1 minuto (Enviados uid
311/312/313), e o terceiro é o que interessa:

> *"Não conseguimos usar o seu áudio. Motivo: Arquivo `1uIeww…TVfd6` não está
> público no Drive (veio página HTML, não o arquivo)."*

**Essa mensagem é exatamente o texto do caso 527** — o falso diagnóstico que em
22/08 mandava aluno "liberar" um link que já estava liberado, corrigido com o
header `Range: bytes=0-` (`drive.ts:88-95` e `151-158`). Então antes de acreditar
no rótulo — e antes de acusar regressão — **fui medir o arquivo, não o ledger**:

| tentativa | desfecho |
|---|---|
| `GET …&export=download&confirm=t` **com** `Range: bytes=0-` (como o código faz hoje) | 302 → `accounts.google.com/ServiceLogin` → 302 → `/v3/signin/identifier` → **200 `text/html`** |
| o mesmo **sem** `Range` | idem, **mesmíssima cadeia** |

**O diagnóstico do sistema está CORRETO e não é regressão do 527.** A prova é
*para onde* o redirect aponta: aqui ele cai em `accounts.google.com/ServiceLogin`,
que é **página de login** — o Drive só manda anônimo pro login quando o recurso
**não é legível publicamente**. O caso 527 era outra coisa: arquivo grande e
público, que respondia `206` com `Range` e devolvia o HTML da confirmação de
antivírus sem ele. Aqui o `Range` **não muda nada**, porque o problema não é
tamanho, é permissão. `drive.ts:101` ("HTML = página de login/erro do Drive
(arquivo privado ou id inválido)") está descrevendo a realidade.

Pela 14-C, **isto não é chamado**: se o código estivesse certo, isso ainda teria
acontecido — o arquivo do aluno realmente não está público. A mensagem que ele
recebeu é correta **e** acionável (diz o que conferir). Não abri incidente e não
escrevi pra ele.

**A decisão que peço ao Johnny** é a que está fora do sistema: é um **pagante do
primeiro dia**, parado há ~6,5h, e **a bola está com ele** — não existe nada no
nosso lado pra destravar, e ninguém está olhando se ele volta. Esse é o churn
caro (paga, trava no dia 1, some). Alguém cutuca hoje ou deixa a automação
esperar o retorno dele?

Uma observação que **não** é acusação, é medida: as imagens dele passaram e o
áudio não, o que bate com material espalhado em pastas com permissões
diferentes — não com "ele não sabe compartilhar".

## 2. O Johnathan segue parado — e agora são DUAS promessas não cumpridas

Não é caso novo (`173` + `180`), então pela 14-C é **ocorrência, não chamado**.
Registro porque o relógio andou e o número mudou.

Na ronda das 10h eu reportei ~6h de espera desde a resposta dele (04:15Z).
Fui ver o que aconteceu desde então: **nada do nosso lado**. Confirmado por dois
caminhos independentes:

- `aluno.cjs johnathan.ppires@gmail.com` → **ainda 0 vozes**, sem acesso,
  −1.575 créditos (débito de onboarding, autorizado a ficar negativo). Nenhuma
  importação nova, nenhum treino disparado.
- Enviados **uid 310, 04:20:18Z**: a Fast respondeu a ele *"Vou pedir pra equipe
  abrir a pasta e te dar o retorno direto sobre o que tem lá e o próximo passo —
  **já já eles respondem** aqui no e-mail."*

São **~8h** desde essa promessa. E é a **segunda** promessa de retorno furada no
mesmo caso: o próprio e-mail de 28/08 21:50 abre com *"Passou o dia e ninguém te
respondeu. Peço desculpa: a demora foi nossa"*. A nota do `173` já registra que
ele foi fechado em 28/08 **1,6s** depois da mensagem do aluno, sem resolução real.

Mantive a fronteira da ronda anterior: **não abri o link do Drive dele**, não
conferi se o material serve, não disparei importação nem treino, não escrevi.
Abrir o Drive e julgar o áudio é trabalho do dono do chamado, não do sensor.

**Alerta que continua valendo pro próximo que pegar:** os arquivos do link ANTIGO
eram peças de divulgação (ACADEMY AD / LAB AD / SOLUTIONS AD). Se o link novo
levar ao mesmo material, **conferir locutor único por F0 antes de disparar
treino** — é a armadilha já medida no caso Marcelo (`f6f82819`), em que o clone
saiu com a voz de outra pessoa. O PR **50** (`feat/guarda-voz-multi-locutor`)
existe exatamente pra isso e está aberto desde 25/08.

## 3. O `182` foi fechado como `ignored` — e eu concordo, sem objeção

Fechado às **12:11:18Z** por `agent`, como `ignored`. É o chamado da rajada de
`no_speech` da `priscillarosseti@hotmail.com` que eu medi na ronda das 10h.

**Não tenho objeção a registrar** (a 14-A me dá esse direito e eu não vou usar):
o fecho bate com o que eu medi no arquivo, não no rótulo — 7 arquivos de 120s com
`mean_volume` = `max_volume` = **−91,0 dB**, silêncio digital absoluto, e o
veredito `no_speech` de `audio_edit.py:352` estava certo. Ela se resolveu sozinha
às 04:48 e o dinheiro está liquidado (7 débitos × 7 estornos, casados por
`ref_id`). **Não reabri e não reclassifiquei.**

O que sobra daquele caso segue sendo o `183`, aberto por mim às 10:18Z e
**intocado** até agora: o defeito não é do Vídeo Estúdio, é de **quem abre o
chamado** — `failure-alert.ts:283-306` chama `openBurstIncident()` antes do portão
`alertSupport` da linha 308, então erro de input que o próprio código já
classificou como não-técnico vira chamado `categoria=tecnico`. **Este fecho de
hoje é mais uma linha na estatística que motivou o `183`**: a `burst-rule` agora
está em 9 `ignored` contra 8 `fixed` desde 17/08 — **53% dos fechados
descartados**, contra o alvo de ≤10% do §5 da 14-C.

## 4. Fechados que voltaram a disparar

**Zero novos.** A única linha com `last_seen_at > resolved_at` na tabela inteira
continua sendo o `#8` ("Treino de voz: áudio insuficiente/sem fala limpa"),
fechado em 09/08, último disparo **22/08 19:26** — 7 dias atrás, mais uma janela
sem se mexer. Segue como registro, sem ação, e **não reabri**.

## 5. Dinheiro — a única falha da janela foi estornada, conferida do jeito certo

Geração `086970cd`, 28/08 18:16:10Z, `executionTimeout exceeded`. É a mesma da
ronda anterior (pré-fix), não é falha nova.

Casada por **`ref_id`**, conferida por **`ref_type`** — nunca por `kind`, nunca
por timestamp (as duas armadilhas da ordem 20/08):

| momento | valor | `ref_type` | `kind` |
|---|---|---|---|
| 18:16:10 | **−400** | `generation` | `generation` |
| 18:24:28 | **+400** | `generation_refund` | **`extra_purchase`** |

Mesmo `ref_id`, liquidado em **8min18s**. Repare no `kind` do estorno:
**`extra_purchase`**. Quem conferir por `kind` conclui que ele não foi estornado
e paga em dobro — é literalmente a armadilha que quase custou 13 alunos.

Estornos na janela de 24h, por `ref_type`: `support_refund` 12 (+12.720),
`studio_audio_refund` 7 (+3.850), `video_clone_refund` 1 (+630),
`image_refund` 1 (+525), `generation_refund` 1 (+400). Nada pendurado.

## 6. Caixa — nenhum e-mail novo de aluno, e o não-lido intocado

`ler_caixa.cjs --ultimos 25 --corpo 2500`: leitura pura (`BODY.PEEK`, só `SEEN`).
**Não toquei em não-lido.** Fila de não-lidos da Fast: **0**.

**Nenhum e-mail novo de aluno desde as 10h.** O mais recente do INBOX continua
sendo o **uid 373** (Johnathan, 04:15Z), já lido na ronda anterior.

Procurei os sinais de escalação silenciosa (*"a equipe vai verificar"*, *"vou
chamar alguém da equipe"*, aluno cobrando 2ª vez): **nenhum caso novo sem
chamado**. Antes de descartar qualquer um, conferi se já havia resposta enviada.

O que mudou está nos **Enviados**, e por isso vale registrar:

- **uid 314, 10:47:15Z, pro Luciano** — *"O retorno tecnico que prometemos: a sua
  foto estava certa"*, abrindo com *"foram 11 horas com você esperando, e isso é
  falha nossa"*. **A pendência que eu levantei na ronda das 00h foi respondida.**
  O `99` segue `investigating`; fechar ou não é do dono, **não mexi**.
- **uid 310, 04:20Z, pro Johnathan** — a promessa do §2.
- **uid 311/312/313, 05:41-05:42Z, pro Luan** — o caso do §1.

## 7. Processo — trabalho não commitado parado na árvore (1 linha, sem chamado)

A árvore de trabalho em `main` está **suja**, com 106 linhas de alteração que não
são minhas e não estão em lugar nenhum do git:

```
 frontend/src/app/api/v1/onboarding/import/route.ts | 15 ++++--
 frontend/src/lib/onboarding/import.ts              | 61 +++++++++++++++++++++-
 frontend/src/lib/onboarding/veredito-audio.ts      | 39 ++++++++++++--
 frontend/src/lib/onboarding/video-audio.ts         (NOVO, não rastreado)
```

É conserto do caminho de onboarding em voo (mesma vizinhança do `146`/`180`).
Pela 14-C isso é **processo**, não chamado: 1 linha aqui + 1 no Telegram. O risco
é concreto e barato de evitar — está sem branch, sem commit e sem PR; um
`checkout` errado leva tudo. **Não toquei**, nem pra `stash`. Meu commit desta
ronda leva **só** o arquivo de prova.

## 8. O que eu NÃO fiz

- Não fechei, não reabri e não reclassifiquei **nenhum** incidente — incluindo o
  `182`, com o qual eu **concordo** (§3).
- **Não abri chamado nenhum nesta ronda.** O caso do §1 foi medido no arquivo e
  reprovou no teste da 14-C ("se o código estivesse certo, isso não teria
  acontecido?" → **não**). Não gastei chamado com ele.
- Não respondi aluno e **não escrevi rascunho de e-mail** (armadilha do lucvila,
  20/08).
- Não toquei em crédito, acesso ou assinatura.
- Não toquei em e-mail não-lido.
- Não mexi em código — nem no meu, nem nas 106 linhas não commitadas do §7.
- Não abri o link do Drive do Johnathan nem disparei importação/treino.
